# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-01 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(blank=True, null=True)),
                ('s_and_p_composite', models.CharField(blank=True, max_length=64, null=True)),
                ('dividend', models.CharField(blank=True, max_length=64, null=True)),
                ('earnings', models.CharField(blank=True, max_length=64, null=True)),
                ('cpi', models.CharField(blank=True, max_length=64, null=True)),
                ('long_interest_rate', models.CharField(blank=True, max_length=64, null=True)),
                ('real_price', models.CharField(blank=True, max_length=64, null=True)),
                ('real_dividend', models.CharField(blank=True, max_length=64, null=True)),
                ('real_earnings', models.CharField(blank=True, max_length=64, null=True)),
                ('cape', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
