# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_auto_20170301_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='equities_growth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
