# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_datapoint_equities_growth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapoint',
            old_name='equities_growth',
            new_name='yearly_equities_growth',
        ),
        migrations.AddField(
            model_name='datapoint',
            name='monthly_equities_growth',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
