# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 14:26
from __future__ import unicode_literals
from decimal import Decimal as D
from django.db import migrations

def populate_yearly_market_gains(apps, schema_editor):
    DataPoint = apps.get_model('market_data', 'DataPoint')
    all_data = DataPoint.objects.all().filter(data_date__month=1).order_by('data_date')
    last_data = None
    for p in all_data:
        if last_data:
            last_years_growth = (D(p.s_and_p_composite) - D(last_data.s_and_p_composite)) / D(
                last_data.s_and_p_composite)
            last_data.yearly_equities_growth = last_years_growth
            last_data.save()
            last_data = p
        else:
            last_data = p

def populate_monthly_market_gains(apps, schema_editor):
    DataPoint = apps.get_model('market_data', 'DataPoint')
    all_data = DataPoint.objects.all()
    last_data = None
    for p in all_data:
        if last_data:
            last_years_growth = (D(p.s_and_p_composite) - D(last_data.s_and_p_composite)) / D(
                last_data.s_and_p_composite)
            last_data.monthly_equities_growth = last_years_growth
            last_data.save()
            last_data = p
        else:
            last_data = p

def undo_populate_yearly_market_gains(apps, schema_editor):
    pass

def undo_populate_monthly_market_gains(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('market_data', '0004_auto_20170316_1926'),
    ]

    operations = [
        migrations.RunPython(populate_yearly_market_gains, undo_populate_yearly_market_gains),
        migrations.RunPython(populate_monthly_market_gains, undo_populate_monthly_market_gains),
    ]
